name: Goose end-end tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run e2e tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        go-version: ["1.19", "1.20", "1.21"]
        dialect: ["postgres", "mysql", "vertica", "clickhouse", "ydb", "turso"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run e2e ${{ matrix.dialect }} tests
        run: |
          if [ ${{ matrix.dialect }} == 'turso' ] && [ ${{ matrix.go-version }} != '1.21' ]; then
            echo "Skipping e2e test for Turso with Go version other than 1.21"
            exit 0
          fi
          make test-e2e-${{ matrix.dialect }}
